services:
  heimdall-ts:
    image: tailscale/tailscale:latest
    hostname: heimdall
    privileged: true
    environment:
      TS_AUTH_KEY: "tskey-auth-kuVCguZ3Bc11CNTRL-WYuaF1zJaMVZoo1uwKcpMVLg3dfCzkKR"
      TS_STATE_DIR: "/var/lib/tailscale"
    volumes:
      - /dev/net/tun:/dev/net/tun
      - heimdall-tailscale-state:/var/lib/tailscale
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    network_mode: "service:heimdall-ts"
    volumes:
      - heimdall-config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    restart: unless-stopped
    depends_on:
      - heimdall-ts

  omada-ts:
    image: tailscale/tailscale:latest
    hostname: omada-controller
    privileged: true
    environment:
      TS_AUTH_KEY: "tskey-auth-kuVCguZ3Bc11CNTRL-WYuaF1zJaMVZoo1uwKcpMVLg3dfCzkKR"
      TS_STATE_DIR: "/var/lib/tailscale"
    volumes:
      - /dev/net/tun:/dev/net/tun
      - omada-tailscale-state:/var/lib/tailscale
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  omada-controller:
    container_name: omada-controller
    image: mbentley/omada-controller:latest
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    stop_grace_period: 60s
    environment:
      USERNAME: "stephenfroeber"
      PGROUP: "omada"
      PUID: "508"
      PGID: "508"
      MANAGE_HTTP_PORT: "8088"
      MANAGE_HTTPS_PORT: "8043"
      PORTAL_HTTP_PORT: "8088"
      PORTAL_HTTPS_PORT: "8843"
      TZ: "America/Chicago"
    volumes:
      - omada-data:/opt/tplink/EAPController/data
      - omada-logs:/opt/tplink/EAPController/logs
    depends_on:
      - omada-ts
    network_mode: "service:omada-ts"

networks:
  homelab:
    driver: bridge

volumes:
  heimdall-config:
    name: "heimdall-config"
    labels:
      - "service=heimdall"
  omada-data:
    name: "omada-data"
    labels:
      - "service=omada-controller"
  omada-logs:
    name: "omada-logs"
    labels:
      - "service=omada-controller"
  heimdall-tailscale-state:
    name: "heimdall-tailscale-state"
    labels:
      - "service=heimdall-ts"
  omada-tailscale-state:
    name: "omada-tailscale-state"
    labels:
      - "service=omada-ts"
