services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - heimdall-config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    restart: unless-stopped
    networks:
      homelab:
        ipv4_address: 192.168.226.101
    mac_address: 02:42:ac:11:00:02

  omada-controller:
    container_name: omada-controller
    image: mbentley/omada-controller:latest
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    stop_grace_period: 60s
    environment:
      USERNAME: "stephenfroeber"
      PGROUP: "omada"
      PUID: "508"
      PGID: "508"
      MANAGE_HTTP_PORT: "8088"
      MANAGE_HTTPS_PORT: "8043"
      PORTAL_HTTP_PORT: "8088"
      PORTAL_HTTPS_PORT: "8843"
      PORT_APP_DISCOVERY: "27001"
      PORT_ADOPT_V1: "29812"
      PORT_UPGRADE_V1: "29813"
      PORT_MANAGER_V1: "29811"
      PORT_MANAGER_V2: "29814"
      PORT_DISCOVERY: "29810"
      PORT_TRANSFER_V2: "29815"
      PORT_RTTY: "29816"
      SHOW_SERVER_LOGS: "true"
      SHOW_MONGODB_LOGS: "false"
      SSL_CERT_NAME: "tls.crt"
      SSL_KEY_NAME: "tls.key"
      TZ: "America/Chicago"
    volumes:
      - omada-data:/opt/tplink/EAPController/data
      - omada-logs:/opt/tplink/EAPController/logs
    ports:
      - "8088:8088"
      - "8043:8043"
      - "27017:27017"
      - "29810:29810/udp"
      - "29811:29811"
      - "29812:29812"
      - "29813:29813"
    mac_address: 02:42:ac:11:00:05
    network_mode: "service:tailscale"
    depends_on:
      - tailscale

  tailscale:
    image: tailscale/tailscale:latest
    hostname: omada-controller
    privileged: true
    environment:
      TS_AUTH_KEY: "tskey-auth-kuVCguZ3Bc11CNTRL-WYuaF1zJaMVZoo1uwKcpMVLg3dfCzkKR"
      TS_STATE_DIR: "/var/lib/tailscale"
    volumes:
      - /dev/net/tun:/dev/net/tun
      - tailscale-state:/var/lib/tailscale
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
    networks:
      homelab:
        ipv4_address: 192.168.226.101
    mac_address: 02:42:ac:11:ad:af

networks:
  homelab:
    driver: macvlan
    driver_opts:
      parent: ens18
    ipam:
      config:
        - subnet: 192.168.226.0/24
          gateway: 192.168.226.1

volumes:
  heimdall-config:
    name: "heimdall-config"
    labels:
      - "service=heimdall"
  omada-data:
    name: "omada-data"
    labels:
      - "service=omada-controller"
  omada-logs:
    name: "omada-logs"
    labels:
      - "service=omada-controller"
  tailscale-state:
    name: "tailscale-state"
    labels:
      - "service=tailscale"
