services:
  # Tailscale sidecar for Heimdall
  heimdall-ts:
    image: tailscale/tailscale:latest
    hostname: heimdall
    networks:
      homelab:
        ipv4_address: 192.168.226.101
        mac_address: 02:42:ac:11:00:04
    environment:
      TS_AUTHKEY: tskey-auth-kuVCguZ3Bc11CNTRL-WYuaF1zJaMVZoo1uwKcpMVLg3dfCzkKR
      TS_EXTRA_ARGS: "--advertise-tags=tag:container --reset"
      TS_STATE_DIR: "/var/lib/tailscale"
      TS_SERVE_CONFIG: "/config/heimdall.json"
    volumes:
      - "/dev/net/tun:/dev/net/tun"
      - "heimdall-tailscale-state:/var/lib/tailscale"
      - "$PWD/tailscale-config:/config"
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  # Heimdall service
  heimdall:
    image: linuxserver/heimdall
    network_mode: service:heimdall-ts
    depends_on:
      - heimdall-ts
    volumes:
      - "$PWD/tailscale-config:/config"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    restart: unless-stopped

  omada-ts:
    image: tailscale/tailscale:latest
    hostname: omada-controller
    networks:
      homelab:
        ipv4_address: 192.168.226.102
        mac_address: 02:42:ac:11:00:05
    environment:
      TS_AUTHKEY: tskey-auth-kuVCguZ3Bc11CNTRL-WYuaF1zJaMVZoo1uwKcpMVLg3dfCzkKR
      TS_EXTRA_ARGS: "--advertise-routes=192.168.226.0/24"
      TS_STATE_DIR: "/var/lib/tailscale"
      TS_SERVE_CONFIG: "/config/omada.json"
    volumes:
      - "/dev/net/tun:/dev/net/tun"
      - "omada-tailscale-state:/var/lib/tailscale"
      - "$PWD/tailscale-config:/config"
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  omada-controller:
    image: mbentley/omada-controller:latest
    volumes:
      - "omada-data:/opt/tplink/EAPController/data"
      - "omada-logs:/opt/tplink/EAPController/logs"
      - "$PWD/tailscale-config:/config"
    network_mode: "service:omada-ts"
    environment:
      USERNAME: "stephenfroeber"
      PGROUP: "omada"
      PUID: "508"
      PGID: "508"
      MANAGE_HTTP_PORT: "8088"
      MANAGE_HTTPS_PORT: "8043"
      PORTAL_HTTP_PORT: "8088"
      PORTAL_HTTPS_PORT: "8843"
      PORT_APP_DISCOVERY: "27001"
      PORT_ADOPT_V1: "29812"
      PORT_UPGRADE_V1: "29813"
      PORT_MANAGER_V1: "29811"
      PORT_MANAGER_V2: "29814"
      PORT_DISCOVERY: "29810"
      PORT_TRANSFER_V2: "29815"
      PORT_RTTY: "29816"
      SHOW_SERVER_LOGS: "true"
      SHOW_MONGODB_LOGS: "false"
      TZ: "America/Chicago"
    restart: unless-stopped

networks:
  homelab:
    driver: macvlan
    driver_opts:
      parent: ens18
    ipam:
      config:
        - subnet: 192.168.226.0/24
          gateway: 192.168.226.1

volumes:
  omada-data:
    driver: local
  omada-logs:
    driver: local
  heimdall-tailscale-state:
    driver: local
  omada-tailscale-state:
    driver: local
