all:
  children:
    proxmox:
      hosts:
        proxmox_server:
          ansible_host: 192.168.226.88
          ansible_port: 8006
          ansible_user: stephenfroeber@pve

    synology:
      hosts:
        synology_nas:
          ansible_host: 192.168.226.6
          ansible_port: 9654
          ansible_user: stephenfroeber
          ansible_ssh_private_key_file: /path/to/your/key

    vms:
      hosts:
        debian_docker_host:
          ansible_host: 192.168.226.100
          ansible_user: coachlight-homelab
          ansible_ssh_pass: "{{ lookup('env', 'VM_PASSWORD') }}"
          ansible_become_pass: "{{ lookup('env', 'VM_PASSWORD') }}"

    docker_services:
      hosts:
        # As you assign static IPs to your Docker services, add them here
        docker_service1:
          ansible_host: 192.168.226.101
          ansible_user: root
          ansible_ssh_private_key_file: /path/to/your/key

  vars:
    ansible_python_interpreter: /usr/bin/python3
