all:
  vars:
    ansible_ssh_private_key_file: ~/.ssh/coachlight-homelab
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local
    proxmox:
      hosts:
        macmini1:
          ansible_host: macmini1.rohu-shark.ts.net
          ansible_user: stephenfroeber
        macmini2:
          ansible_host: macmini2.rohu-shark.ts.net
          ansible_user: stephenfroeber

    nas:
      hosts:
        synology_nas:
          ansible_host: srfaudio.rohu-shark.ts.net
          ansible_user: stephenfroeber

    vms:
      hosts:
        debian_docker_host:
          ansible_host: debian-docker-host-vm.rohu-shark.ts.net
          ansible_user: sfroeber
